name: New Issue
description: Follow this template.
body:
  - type: input
    id: specific-mod
    attributes:
      label: Specific mod for which you open this issue
      placeholder: e.g. GhostJump
    validations:
      required: true
  - type: input
    id: version-info
    attributes:
      label: MC version & mod version
      placeholder: e.g. mc1165, mod v1.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Latest log
      description: "Use [gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc instead of spamming them here."
